[package]
name = "dev_manifest_finder"
version = "0.6.0"
authors = ["jlgerber <jlgerber@gmail.com>"]
edition = "2018"

[dependencies]
pes_core = { path = "../pes_core", version = "*" }

[lib]
name = "manifest_finder"
crate-type = ["dylib"]