[package]
name = "pes"
version = "0.2.0"
authors = ["jgerber"]
edition = "2018"


[dependencies]
itertools = "0.10.0"
log = "0.4.14"
nix = "0.20.0"
peslib = {path = "../peslib" }
pretty_env_logger = "0.4.0"
structopt = "0.3.21"
users = "0.11.0"
