[package]
name = "pes"
version = "0.1.0"
authors = ["jgerber"]
edition = "2018"


[dependencies]
log = "0.4.14"
#main_error = "0.1.1"
peslib = {path = "../peslib" }
pretty_env_logger = "0.4.0"
structopt = "0.3.21"
