[package]
name = "repo_finder"
version = "0.1.0"
authors = ["jlgerber <jlgerber@gmail.com>"]
edition = "2018"

[dependencies]
pes_interface = { path = "../pes_interface", version = "*" }

[lib]
name = "repo_finder"
crate-type = ["dylib"]
