[package]
name = "repo_finder"
version = "0.1.0"
authors = ["jlgerber <jlgerber@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "3.0"
log = "0.4"
pes_interface = { path = "../pes_interface", version = "*" }
users = "0.11"

[lib]
name = "repo_finder"
crate-type = ["dylib"]
